//
//  Images.h
//  BrickBreaker
//
//  Created by Kenneth Wilcox on 10/21/14.
//  Copyright (c) 2014 Kenneth Wilcox. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface Images : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* gamePaddleTargets;

// Colors
+ (UIColor*)lightColor;
+ (UIColor*)bottomColor;
+ (UIColor*)edgeColor;
+ (UIColor*)topColor;
+ (UIColor*)darkColor;

// Drawing Methods
+ (void)drawGamePaddle;

// Generated Images
+ (UIImage*)imageOfGamePaddle;

@end
